"""Chaves do Claviculario FMO (slots 1-99)."""

FMO_KEYS: list[str] = [
    "01 - Cafe",
    "02 - Estacionamento",
    "03 - Bilheteria",
    "04 - Salas Operacionais",
    "05 - SSO / PCL",
    "06 - Espaco Acolher",
    "07 - Sanitario Publico PCD Feminino",
    "08 - Sanitario Publico PCD Masculino",
    "09 - Balcoes das Bilheterias",
    "10 - Sala de Convivencia",
    "11 - Sala Operacional",
    "12 - Copa CPTM",
    "13 - Sala SGE",
    "14 - Vestiario Masculino CPTM",
    "15 - Sanitario Masculino CPTM",
    "16 - Vestiario Feminino CPTM",
    "17 - Sanitario Feminino CPTM",
    "18 - Sanitario Masculino PCD CPTM",
    "19 - Sanitario Feminino PCD CPTM",
    "20 - Sala de Apoio",
    "21 - Resgate EL01",
    "22 - Resgate EL02",
    "23 - Painel Comando Elevadores",
    "24 - Cabine Elevadores",
    "25 - Abrigo Painel EL01",
    "26 - Abrigo Painel EL02",
    "27 - Porta de Vidro EL03",
    "28 - Portoes de correr Jardim Suspenso",
    "29 - E.R. 01 a 05 (Painel Controle)",
    "30 - Armario ER01",
    "31 - Armario ER02",
    "32 - Armario ER03",
    "33 - Armario ER04",
    "34 - Armario ER05",
    "35 - Bloqueios",
    "36 - Chave de Trem",
    "37 - Deposito Elevador 03",
    "38 - Portas manutencao SSO",
    "39 - Cavalete SABESP",
    "40 - Abrigo de abast. de emergencia",
    "41 - Sala Tecnica Sinalizacao",
    "42 - Sala Tecnica Telecom",
    "43 - Sala Tecnica Gerador",
    "44 - Sala Tecnica Baixa Tensao",
    "45 - Sala Tecnica Media Tensao",
    "46 - Sala de Baterias",
    "47 - Porao Plataforma 1",
    "48 - Porao Plataforma 2 e 3",
    "49 - Raque Plataforma 1 - ao lado E.R. 04",
    "50 - Sala Tecnica Plataforma 1",
    "51 - Raques Plataformas 1, 2 e 3",
    "52 - Portao + Cadeado + Cabine Primaria",
    "53 - Portoes de entrada da estacao",
    "54 - Portao ao lado salas tecnicas e ATM's",
    "55 - Chave Padrao Painel",
    "56 - Chave Porta Fusivel",
    "57 - Alarme de Incendio",
    "58 - Chave do detector de incendio - Sala Tecnica",
    "59 - Painel Gerador",
    "60 - Portao Estacionam. Salas Tecnicas",
    "61 - Cacambas de lixo",
    "62 - Rota de fuga plataforma: RAMPA",
    "63 - Armario Aco (Apoio Operac.)",
    "64 - Guarita Estacionamento",
    "65 - Papeleiras",
    "66 - Porta interna DML",
    "67 - Sanitario Sala de Apoio Plat. 02",
    "68 - Sanitario Publico Masculino",
    "69 - Sanitario Publico Feminino",
    "70 - DML",
    "71 - Sala de Apoio Plat. 01 / TRANSB",
    "72 - Sala de Apoio Plat. 02 e 03 / TRANSB",
    "73 - Porta lateral DML",
    "74 - Guarita Patio Norte",
    "75 - LDM - Fisc. Limpeza / Armario 31",
    "76 - Arquivo da Sala Operacional",
    "77 - Porao ER 02",
    "78 - Porao ER 03",
    "79 - Porao ER 04",
    "80 - Porao ER 05",
    "81 - Caixa D'agua - GS FMO",
    "82 - Armario Sanitarios Publicos",
    "83 - Sanitario Sala de Apoio Plat. 01",
    "84 - Abrigo caixas de inox Patio Norte",
    "85 - Abrigo de disjuntores Patio Norte",
    "86 - Armario ao lado sala de apoio Plat. 2",
    "87 - Raque Plataforma 02 - ao lado da E.R. 05",
    "88 - Abrigos e Caixas Jardim Suspenso",
    "89 - Triangulo caixa de telefone",
    "90 - Base da Tejofran Patio Norte",
    "91 - Sinalizacao Patio Norte",
    "92 - Caixa de Inspecao - Patio Sul",
    "93 - Canteiro de Obras",
    "94 - Porta embaixo da E.R. do terminal",
    "95 - Copia Estacionamento",
    "96 - Gaveteiros SSO",
    "97 - Reserva Armario Feminino",
    "98 - Reserva Armario Masculino",
    "99 - Guarita Estacionamento",
]
